### ISSUE TITLE
ERROR: Failed building wheel for scipy on python 3.8

### ISSUE THREAD

**Issue by he7d3r** [wikimedia/articlequality#116]
On Linux Mint 19.3, after I cloned
https://github.com/wikimedia/articlequality
and created/activated a new environment with
```bash
$ conda create -n articlequality pip
$ conda activate articlequality
```
I had some trouble installing articlequality with the command
```bash
$ pip install -r requirements.txt
```
During the process, it displayed `ERROR: Failed building wheel for scipy`. Once it finished, I attempted to run
```bash
$ python -c "import articlequality"
```
but I got
```bas
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/helder/projects/articlequality/articlequality/__init__.py", line 2, in <module>
    from .utilities.extract_from_text import extract_from_text
  File "/home/helder/projects/articlequality/articlequality/utilities/extract_from_text.py", line 41, in <module>
    from revscoring import Dependent
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/revscoring/__init__.py", line 149, in <module>
    from .scoring import Model
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/revscoring/scoring/__init__.py", line 25, in <module>
    from .models.model import Model
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/revscoring/scoring/models/__init__.py", line 38, in <module>
    from .gradient_boosting import GradientBoosting
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/revscoring/scoring/models/gradient_boosting.py", line 10, in <module>
    from sklearn.ensemble import GradientBoostingClassifier
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/sklearn/__init__.py", line 64, in <module>
    from .base import clone
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/sklearn/base.py", line 14, in <module>
    from .utils.fixes import signature
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 14, in <module>
    from . import _joblib
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/sklearn/utils/_joblib.py", line 22, in <module>
    from ..externals import joblib
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/sklearn/externals/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/sklearn/externals/joblib/parallel.py", line 28, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 22, in <module>
    from .executor import get_memmapping_executor
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/sklearn/externals/joblib/executor.py", line 14, in <module>
    from .externals.loky.reusable_executor import get_reusable_executor
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/sklearn/externals/joblib/externals/loky/__init__.py", line 12, in <module>
    from .backend.reduction import set_loky_pickler
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/sklearn/externals/joblib/externals/loky/backend/reduction.py", line 125, in <module>
    from sklearn.externals.joblib.externals import cloudpickle  # noqa: F401
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 167, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/home/helder/miniconda3/envs/articlequality/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 148, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)
```

After searching around, I found out at https://github.com/scikit-learn/scikit-learn/issues/15800#issuecomment-562370145 that I would have to downgrade from python3.8 to python3.7. I was then able to finish the installation only when I used this instead:
```bash
$ conda create -n articlequality python=3.7 pip
```
Is this info something that should be added somewhere in the repo?

**Comment by he7d3r** [comment]
[full-instalattion.log](https://github.com/wikimedia/articlequality/files/4452031/full-instalattion.log)

**Comment by halfak** [comment]
Interesting.  On the face of it, it looks like an sklearn issue.

**Comment by halfak** [comment]
Aha.  Nevermind.  It looks like a joblib issue.  The best way to get around this is to bump the version sklearn we support in revscoring.

**Comment by he7d3r** [comment]
I assume this is fixed by the latest updates, as I was able to run
```
conda create -n articlequality python=3.8 pip
conda activate articlequality
pip install -r requirements.txt
python -c "import articlequality"
```
without the `TypeError` reported above.
