### ISSUE TITLE
UnpicklingError on example code

### ISSUE THREAD

**Issue by gi11es** [wikimedia/articlequality#79]
```
~/Documents/Mediawiki/articlequality (master) $ python3
Python 3.7.1 (default, Nov 26 2018, 12:31:31) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import articlequality
/usr/local/lib/python3.7/site-packages/scikit_learn-0.19.2-py3.7-macosx-10.14-x86_64.egg/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
>>> from revscoring import Model 
>>> scorer_model = Model.load(open("models/enwiki.nettrom_wp10.gradient_boosting.model", "rb"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/revscoring-2.3.4-py3.7.egg/revscoring/scoring/models/model.py", line 104, in load
    model = pickle.load(f)
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by halfak** [comment]
Sorry for the incredibly late reply.  It looks like this issue is because of git-lfs.  When you don't have it installed or you have not told it to pull down the actual files, it instead pulls down files with reference information.  Try installing git-lfs and doing a "git pull" and try again.

**Comment by gi11es** [comment]
I don't think I have that checkout anymore, that was on a different computer, so can't verify the fix, sorry.

**Comment by he7d3r** [comment]
I was having the same problem, and after
```
sudo apt-get install git-lfs
git lfs install --local
git lfs pull
```
I was able to get this:
```python
$ python
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import articlequality
>>> from revscoring import Model
>>> scorer_model = Model.load(open("models/enwiki.nettrom_wp10.gradient_boosting.model", "rb"))
Differences between the current environment and the environment in which the model was constructed environment were detected:
 - python_compiler 'GCC 6.3.0 20170516' mismatch with original environment 'GCC 7.3.0'
 - release '4.9.0-11-amd64' mismatch with original environment '5.4.0-26-generic'
 - python_version '3.5.3' mismatch with original environment '3.5.6'
 - revscoring_version '2.6.2' mismatch with original environment '2.6.9'
 - processor '' mismatch with original environment 'x86_64'
 - version '#1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20)' mismatch with original environment '#30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020'
 - platform 'Linux-4.9.0-11-amd64-x86_64-with-debian-9.11' mismatch with original environment 'Linux-5.4.0-26-generic-x86_64-with-debian-bullseye-sid'
 - python_build ('default', 'Sep 27 2018 17:25:39') mismatch with original environment ('default', 'Aug 26 2018 21:41:56')
```

**Comment by halfak** [comment]
Thanks @he7d3r
