### ISSUE TITLE
tokenizer errors in extract_scores -- helpful to get reports?

### ISSUE THREAD

**Issue by kayleachampion** [wikimedia/articlequality#80]
Hi, I forgot to report these when they came up for me a month ago, running your tools against our local archive. 

If it's relevant, my calls to article_quality look like 500+ examples of this:

articlequality extract_scores /path/to/enwiki-20180301-pages-meta-history8.xml-p1768132p1791079.bz2 --model=/path/to/enwiki.nettrom_wp10.gradient_boosting.model --score-at=monthly --sunset=20181231000000 --rev-scores="/path/to/outfile0.txt" 2> /path/to/error0.txt 

Since the message instructs me to report them, I thought I would -- also not sure if you want the full trace but here you go just in case.

=================several revs from this French super series article==================

2019-01-17 23:51:24,182 ERROR:articlequality.utilities.extract_scores -- Error while processing 2015 French Super Series(47684588) @ 687747133: ParserError: Failed to process datasource.wikitext.revision
.wikicode: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.
Traceback (most recent call last):
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/dependencies/functions.py", line 244, in _solve
    value = dependent(*args)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/dependencies/dependent.py", line 54, in __call__
    return self.process(*args, **kwargs)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/features/wikitext/datasources/parsed.py", line 210, in _process_wikicode
    return mwparserfromhell.parse(text)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/mwparserfromhell-0.5.2-py3.5-linux-x86_64.egg/mwparserfromhell/utils.py", line 58, in parse_anything
    return Parser().parse(value, context, skip_style_tags)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/mwparserfromhell-0.5.2-py3.5-linux-x86_64.egg/mwparserfromhell/parser/__init__.py", line 93, in parse
    tokens = self._tokenizer.tokenize(text, context, skip_style_tags)
mwparserfromhell.parser.ParserError: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.

2019-01-17 23:52:39,671 ERROR:articlequality.utilities.extract_scores -- Error while processing 2015 French Super Series(47684588) @ 715981732: ParserError: Failed to process datasource.wikitext.revision
.wikicode: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.
Traceback (most recent call last):
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/dependencies/functions.py", line 244, in _solve
    value = dependent(*args)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/dependencies/dependent.py", line 54, in __call__
    return self.process(*args, **kwargs)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/features/wikitext/datasources/parsed.py", line 210, in _process_wikicode
    return mwparserfromhell.parse(text)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/mwparserfromhell-0.5.2-py3.5-linux-x86_64.egg/mwparserfromhell/utils.py", line 58, in parse_anything
    return Parser().parse(value, context, skip_style_tags)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/mwparserfromhell-0.5.2-py3.5-linux-x86_64.egg/mwparserfromhell/parser/__init__.py", line 93, in parse
    tokens = self._tokenizer.tokenize(text, context, skip_style_tags)
mwparserfromhell.parser.ParserError: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.

2019-01-17 23:53:19,010 ERROR:articlequality.utilities.extract_scores -- Error while processing 2015 French Super Series(47684588) @ 725711614: ParserError: Failed to process datasource.wikitext.revision
.wikicode: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.
Traceback (most recent call last):
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/dependencies/functions.py", line 244, in _solve
    value = dependent(*args)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/dependencies/dependent.py", line 54, in __call__
    return self.process(*args, **kwargs)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/features/wikitext/datasources/parsed.py", line 210, in _process_wikicode
    return mwparserfromhell.parse(text)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/mwparserfromhell-0.5.2-py3.5-linux-x86_64.egg/mwparserfromhell/utils.py", line 58, in parse_anything
    return Parser().parse(value, context, skip_style_tags)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/mwparserfromhell-0.5.2-py3.5-linux-x86_64.egg/mwparserfromhell/parser/__init__.py", line 93, in parse
    tokens = self._tokenizer.tokenize(text, context, skip_style_tags)
mwparserfromhell.parser.ParserError: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.

2019-01-17 23:53:56,713 ERROR:articlequality.utilities.extract_scores -- Error while processing 2015 French Super Series(47684588) @ 759850861: ParserError: Failed to process datasource.wikitext.revision
.wikicode: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.
Traceback (most recent call last):
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/dependencies/functions.py", line 244, in _solve
    value = dependent(*args)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/dependencies/dependent.py", line 54, in __call__
    return self.process(*args, **kwargs)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/features/wikitext/datasources/parsed.py", line 210, in _process_wikicode
    return mwparserfromhell.parse(text)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/mwparserfromhell-0.5.2-py3.5-linux-x86_64.egg/mwparserfromhell/utils.py", line 58, in parse_anything
    return Parser().parse(value, context, skip_style_tags)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/mwparserfromhell-0.5.2-py3.5-linux-x86_64.egg/mwparserfromhell/parser/__init__.py", line 93, in parse
    tokens = self._tokenizer.tokenize(text, context, skip_style_tags)
mwparserfromhell.parser.ParserError: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.
2019-01-17 23:54:32,963 ERROR:articlequality.utilities.extract_scores -- Error while processing 2015 French Super Series(47684588) @ 775622575: ParserError: Failed to process datasource.wikitext.revision
.wikicode: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.
Traceback (most recent call last):
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/dependencies/functions.py", line 244, in _solve
    value = dependent(*args)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/dependencies/dependent.py", line 54, in __call__
    return self.process(*args, **kwargs)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/features/wikitext/datasources/parsed.py", line 210, in _process_wikicode
    return mwparserfromhell.parse(text)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/mwparserfromhell-0.5.2-py3.5-linux-x86_64.egg/mwparserfromhell/utils.py", line 58, in parse_anything
    return Parser().parse(value, context, skip_style_tags)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/mwparserfromhell-0.5.2-py3.5-linux-x86_64.egg/mwparserfromhell/parser/__init__.py", line 93, in parse
    tokens = self._tokenizer.tokenize(text, context, skip_style_tags)
mwparserfromhell.parser.ParserError: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.

2019-01-17 23:55:10,342 ERROR:articlequality.utilities.extract_scores -- Error while processing 2015 French Super Series(47684588) @ 780647959: ParserError: Failed to process datasource.wikitext.revision
.wikicode: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.
Traceback (most recent call last):
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/dependencies/functions.py", line 244, in _solve
    value = dependent(*args)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/dependencies/dependent.py", line 54, in __call__
    return self.process(*args, **kwargs)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/features/wikitext/datasources/parsed.py", line 210, in _process_wikicode
    return mwparserfromhell.parse(text)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/mwparserfromhell-0.5.2-py3.5-linux-x86_64.egg/mwparserfromhell/utils.py", line 58, in parse_anything
    return Parser().parse(value, context, skip_style_tags)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/mwparserfromhell-0.5.2-py3.5-linux-x86_64.egg/mwparserfromhell/parser/__init__.py", line 93, in parse
    tokens = self._tokenizer.tokenize(text, context, skip_style_tags)
mwparserfromhell.parser.ParserError: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.

2019-01-17 23:55:46,078 ERROR:articlequality.utilities.extract_scores -- Error while processing 2015 French Super Series(47684588) @ 796215330: ParserError: Failed to process datasource.wikitext.revision
.wikicode: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.
Traceback (most recent call last):
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/dependencies/functions.py", line 244, in _solve
    value = dependent(*args)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/dependencies/dependent.py", line 54, in __call__
    return self.process(*args, **kwargs)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/features/wikitext/datasources/parsed.py", line 210, in _process_wikicode
    return mwparserfromhell.parse(text)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/mwparserfromhell-0.5.2-py3.5-linux-x86_64.egg/mwparserfromhell/utils.py", line 58, in parse_anything
    return Parser().parse(value, context, skip_style_tags)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/mwparserfromhell-0.5.2-py3.5-linux-x86_64.egg/mwparserfromhell/parser/__init__.py", line 93, in parse
    tokens = self._tokenizer.tokenize(text, context, skip_style_tags)
mwparserfromhell.parser.ParserError: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.

===========also from this National Football League (Ireland) article==============

2019-01-18 07:21:08,411 ERROR:articlequality.utilities.extract_scores -- Error while processing 2010 National Football League (Ireland)(22884451) @ 352612341: ParserError: Failed to process datasource.wi
kitext.revision.wikicode: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.
Traceback (most recent call last):
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/dependencies/functions.py", line 244, in _solve
    value = dependent(*args)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/dependencies/dependent.py", line 54, in __call__
    return self.process(*args, **kwargs)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/revscoring-2.3.0-py3.5.egg/revscoring/features/wikitext/datasources/parsed.py", line 210, in _process_wikicode
    return mwparserfromhell.parse(text)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/mwparserfromhell-0.5.2-py3.5-linux-x86_64.egg/mwparserfromhell/utils.py", line 58, in parse_anything
    return Parser().parse(value, context, skip_style_tags)
  File "/usr/lusers/kaylea/.local/lib64/python3.5/site-packages/mwparserfromhell-0.5.2-py3.5-linux-x86_64.egg/mwparserfromhell/parser/__init__.py", line 93, in parse
    tokens = self._tokenizer.tokenize(text, context, skip_style_tags)
mwparserfromhell.parser.ParserError: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.

**Comment by halfak** [comment]
Thank you!  I've copied this over to https://github.com/earwig/mwparserfromhell/issues/224
